services:
  server1:
    restart: always
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server1
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - server1_data:/data
      - server1_logs:/logs
      - server1_conf:/conf
      - server1_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=PRIMARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"

  server2:
    restart: always
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server2
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - server2_data:/data
      - server2_logs:/logs
      - server2_conf:/conf
      - server2_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

  server3:
    restart: always
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server3
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - server3_data:/data
      - server3_logs:/logs
      - server3_conf:/conf
      - server3_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

volumes:
  server1_data:
  server1_logs:
  server1_conf:
  server1_import:
  server2_data:
  server2_logs:
  server2_conf:
  server2_import:
  server3_data:
  server3_logs:
  server3_conf:
  server3_import:

networks:
  shared:
    external: true
