services:
  neo4j:
    container_name: neo4j
    restart: always
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=10G
      - NEO4J_server_memory_heap_max__size=14G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_import:/import
    hostname: neo4j
    networks:
      - shared
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_import:

networks:
  shared:
    external: true