services:
  server1:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server1
    networks:
      - shared-network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server1:/data
      - ./logs/server1:/logs
      - ./conf/server1:/conf
      - ./import/server1:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=PRIMARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"

  server2:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server2
    networks:
      - shared-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server2:/data
      - ./logs/server2:/logs
      - ./conf/server2:/conf
      - ./import/server2:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

  server3:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server3
    networks:
      - shared-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./data/server3:/data
      - ./logs/server3:/logs
      - ./conf/server3:/conf
      - ./import/server3:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

networks:
  shared:
    external: true