services:
  neo4j:
    container_name: neo4j
    restart: always
    image: neo4j:5.24.2
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=10G
      - NEO4J_server_memory_heap_max__size=16G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_import:/import
    hostname: neo4j
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"
    networks:
      - shared

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_import:

networks:
  shared:
    external: true