version: '3.8'

networks:
  shared-network:
    external: true

services:
  lineage-backend-1:
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8081:8080"
    networks:
      - shared-network

  lineage-backend-2:
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8082:8080"
    networks:
      - shared-network

  lineage-backend-3:
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8083:8080"
    networks:
      - shared-network
