services:
  lineage-backend-1:
    container_name: backend-1
    restart: always
    image: floriansdocker/lineage-backend:1.0.10
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    networks:
      - shared

  lineage-backend-2:
    restart: always
    container_name: backend-2
    image: floriansdocker/lineage-backend:1.0.10
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    networks:
      - shared

  lineage-backend-3:
    restart: always
    container_name: backend-3
    image: floriansdocker/lineage-backend:1.0.10
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    networks:
      - shared

networks:
  shared:
    external: true