services:
  lineage-backend-1:
    restart: always
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8081:8080"
    networks:
      - shared

  lineage-backend-2:
    restart: always
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8082:8080"
    networks:
      - shared

  lineage-backend-3:
    restart: always
    image: lineage-backend:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512m"
    ports:
      - "8083:8080"
    networks:
      - shared

networks:
  shared:
    external: true