services:
  neo4j-1:
    container_name: neo4j-1-cluster
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: neo4j-1
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - neo4j-cluster-1_data:/data
      - neo4j-cluster-1_logs:/logs
      - neo4j-cluster-1_conf:/conf
      - neo4j-cluster-1_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=PRIMARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"

  neo4j-2:
    container_name: neo4j-2-cluster
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: neo4j-2
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - neo4j-cluster-2_data:/data
      - neo4j-cluster-2_logs:/logs
      - neo4j-cluster-2_conf:/conf
      - neo4j-cluster-2_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

  neo4j-3:
    container_name: neo4j-3-cluster
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: neo4j-3
    networks:
      shared:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - neo4j-cluster-3_data:/data
      - neo4j-cluster-3_logs:/logs
      - neo4j-cluster-3_conf:/conf
      - neo4j-cluster-3_import:/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    user: ${USER_ID}:${GROUP_ID}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "12g"

volumes:
  neo4j-cluster-1_data:
  neo4j-cluster-1_logs:
  neo4j-cluster-1_conf:
  neo4j-cluster-1_import:
  neo4j-cluster-2_data:
  neo4j-cluster-2_logs:
  neo4j-cluster-2_conf:
  neo4j-cluster-2_import:
  neo4j-cluster-3_data:
  neo4j-cluster-3_logs:
  neo4j-cluster-3_conf:
  neo4j-cluster-3_import:

networks:
  shared:
    external: true
