services:
  spark-master-lineage:
    restart: always
    container_name: spark-master-lineage
    image: floriansdocker/spark-lineage:3.5.3.5
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-1-lineage:
    restart: always
    container_name: spark-worker-1-lineage
    image: floriansdocker/spark-lineage:3.5.3.5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-lineage:7077
    ports:
      - "9500:8081"
    depends_on:
      - spark-master-lineage
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

  spark-worker-2-lineage:
    restart: always
    container_name: spark-worker-2-lineage
    image: floriansdocker/spark-lineage:3.5.3.5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-lineage:7077
    ports:
      - "9501:8081"
    depends_on:
      - spark-master-lineage
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

  spark-worker-3-lineage:
    restart: always
    container_name: spark-worker-3-lineage
    image: floriansdocker/spark-lineage:3.5.3.5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-lineage:7077
    ports:
      - "9502:8081"
    depends_on:
      - spark-master-lineage
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

networks:
  shared:
    external: true