services:
  spark-master:
    restart: always
    container_name: spark-master-lineage
    image: floriansdocker/spark-lineage:1.0.4
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-1:
    restart: always
    container_name: spark-worker-1-lineage
    image: floriansdocker/spark-lineage:1.0.4
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-2:
    restart: always
    container_name: spark-worker-2-lineage
    image: floriansdocker/spark-lineage:1.0.4
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-3:
    restart: always
    container_name: spark-worker-3-lineage
    image: floriansdocker/spark-lineage:1.0.2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

networks:
  shared:
    external: true