services:
  spark-master:
    restart: always
    container_name: spark-master
    image: floriansdocker/spark:3.5.3.0
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-1:
    restart: always
    container_name: spark-worker-1
    image: floriansdocker/spark:3.5.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

  spark-worker-2:
    restart: always
    container_name: spark-worker-2
    image: floriansdocker/spark:3.5.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

  spark-worker-3:
    restart: always
    container_name: spark-worker-3
    image: floriansdocker/spark:3.5.3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "10g"
    networks:
      - shared

networks:
  shared:
    external: true