services:
  spark-master-unmodified:
    image: bitnami/spark:latest
    container_name: spark-master-unmodified
    hostname: spark-master-unmodified
    ports:
      - "8080:8080"   # Spark Web UI
      - "7077:7077"   # Spark master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-1-unmodified:
    image: bitnami/spark:latest
    container_name: spark-worker-1-unmodified
    hostname: spark-worker-1-unmodified
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-unmodified:7077
#      - SPARK_WORKER_MEMORY=8G
#      - SPARK_WORKER_CORES=2
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-2-unmodified:
    image: bitnami/spark:latest
    container_name: spark-worker-2-unmodified
    hostname: spark-worker-2-unmodified
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-unmodified:7077
#      - SPARK_WORKER_MEMORY=8G
#      - SPARK_WORKER_CORES=2
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

  spark-worker-3-unmodified:
    image: bitnami/spark:latest
    container_name: spark-worker-3-unmodified
    hostname: spark-worker-3-unmodified
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-unmodified:7077
#      - SPARK_WORKER_MEMORY=8G
#      - SPARK_WORKER_CORES=2
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8g"
    networks:
      - shared

networks:
  shared:
    external: true