services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - namenode_data:/hadoop/dfs/name
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - shared

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9866:9866
    volumes:
      - datanode1_data:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - shared

volumes:
  namenode_data:
  datanode1_data:

networks:
  shared:
    external: true
